version: 2.1

jobs:
  build_and_test:
    docker:
      - image: python:3.11
    environment:
      LD_LIBRARY_PATH: /usr/local/lib/instantclient
      ORACLE_HOME: /usr/local/lib/instantclient
      DB_USER: system
      DB_PASSWORD: 1234
      DB_DSN: localhost:1521/ORCL
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y libaio1 unzip curl

      - run:
          name: Install Oracle Instant Client from local zip
          command: |
            unzip instantclient-basic-linux.x64-23.8.0.25.04.zip -d /usr/local/lib
            ln -s /usr/local/instantclient_23_8 /usr/local/lib/instantclient

      - run:
          name: Install Python dependencies
          command: |
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt

      - run:
          name: Run pytest
          command: |
            export LD_LIBRARY_PATH=/usr/local/lib/instantclient
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
