version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10  # Just to run docker CLI
    steps:
      - checkout

      - setup_remote_docker  # Needed to build and run Docker images

      - run:
          name: Build Docker Image
          command: |
            docker build -t my-flask-app .

      - run:
          name: Run Pytest inside container
          command: |
            docker run --rm my-flask-app pytest

workflows:
  version: 2
  test_and_build:
    jobs:
      - build-and-test
